version: "3.9"

services:
  auth:
    build: ./auth
    container_name: auth
    ports:
      - "3001:3000"
    networks:
      - backend


  wellness:
    build: ./wellness
    container_name: wellness
    ports:
      - "3002:3000"
    networks:
      - backend

  care:
    build: ./care
    container_name: care
    ports:
      - "3003:3000"
    networks:
      - backend

  community:
    build: ./community
    container_name: community
    ports:
      - "3004:3000"
    networks:
      - backend

  progress:
    build: ./progress
    container_name: progress
    ports:
      - "3005:3000"
    networks:
      - backend
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sunstonemind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  custom-nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - wellness
      - care
      - community
      - progress
    networks:
      - backend

networks:
  backend:


volumes:
  pgdata:
